import { StyledRegistry } from '@/styles/registry/styled-registry';
import './globals.css';
import { Inter } from 'next/font/google';
import Navigation from '@/components/Navbar/Navigation';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <head>
        <title>Evo Tech Test Blog</title>
      </head>
      <Navigation />
      <body className={inter.className}>
        <StyledRegistry>{children}</StyledRegistry>
      </body>
    </html>
  );
}
